# Generated by Django 2.2.16 on 2022-11-12 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20221112_0149'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_members',
        ),
    ]
